/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package apphotel;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author untac
 */
public class Inlistaprecios extends javax.swing.JFrame {

    /**
     * Creates new form Inlistaprecios
     */
    public Inlistaprecios() {
        initComponents();
        if (!Inlogin.TipoUser) {
            jButtonModSele.setEnabled(false);
        }

        Iter.Preespora.add("40000");
        Iter.Preespora.add("50000");
        Iter.Preespora.add("80000");
        Iter.Preehabitual.add("50000");
        Iter.Preehabitual.add("70000");
        Iter.Preehabitual.add("100000");
        DefaultTableModel Mtable = (DefaultTableModel) jTablelista.getModel();
        Mtable.addRow(new Object[]{"SIMPLE", Iter.Preehabitual.get(0).toString(), Iter.Preespora.get(0).toString()});
        Mtable.addRow(new Object[]{"DOBLE", Iter.Preehabitual.get(1).toString(), Iter.Preespora.get(1).toString()});
        Mtable.addRow(new Object[]{"MATRIMONIAL", Iter.Preehabitual.get(2).toString(), Iter.Preespora.get(2).toString()});
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTablelista = new javax.swing.JTable();
        jButtonModSele = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTablelista.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "tipos de habitacion", "clientes habitual", "clientes esporadicos"
            }
        ));
        jScrollPane1.setViewportView(jTablelista);

        jButtonModSele.setText("Modificar selección");
        jButtonModSele.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModSeleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonModSele)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonModSele)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonModSeleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModSeleActionPerformed
        // TODO add your handling code here:
        DefaultTableModel Mtable = (DefaultTableModel) jTablelista.getModel();
        ArrayList DatosTable = new ArrayList();

        for (int i = 0; i < jTablelista.getRowCount(); i++) {
            for (int j = 0; j < jTablelista.getColumnCount(); j++) {
                DatosTable.add(jTablelista.getValueAt(i, j));
                System.out.print(jTablelista.getValueAt(i, j) + "-");
            }
            System.out.println();
        }
        Iter.ValDobleespo = DatosTable.get(5).toString();
        Iter.ValDoblehabi = DatosTable.get(4).toString();
        Iter.ValSimpespo = DatosTable.get(2).toString();
        Iter.ValSimphabi = DatosTable.get(1).toString();
        Iter.ValMatriespo = DatosTable.get(8).toString();
        Iter.ValMatrihabi = DatosTable.get(7).toString();
        Iter.Preespora.add(0, DatosTable.get(2));
        Iter.Preespora.add(1, DatosTable.get(5));
        Iter.Preespora.add(2, DatosTable.get(8));
        Iter.Preehabitual.add(0, DatosTable.get(1));
        Iter.Preehabitual.add(1, DatosTable.get(4));
        Iter.Preehabitual.add(2, DatosTable.get(7));
        System.out.println("datos dentro del array " + DatosTable);
        //JOptionPane.showMessageDialog(null, "datos seleccionado de la tabla " + codigo);
        Mtable.fireTableDataChanged();
        //jTablelista.removeRowSelectionInterval(0,2);
        //Mtable = new JTable();
        //jTablelista(new JTable);
    }//GEN-LAST:event_jButtonModSeleActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inlistaprecios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inlistaprecios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inlistaprecios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inlistaprecios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inlistaprecios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonModSele;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTablelista;
    // End of variables declaration//GEN-END:variables
}
