/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package apphotel;

/**
 *
 * @author untac
 */
public class ReseHabitaciones extends javax.swing.JFrame {

    /**
     * Creates new form ReseHabitaciones
     */
    public ReseHabitaciones() {
        initComponents();
        buttonGroupHabit.add(jRadioButtonSim);
        buttonGroupHabit.add(jRadioButtondolb);
        buttonGroupHabit.add(jRadioButtonmatr);
        for (int i = 0; Iter.hasimples.size() > i; i++) {
            jComboBoxSim.addItem(Iter.hasimples.get(i).toString());
        }
        for (int i = 0; Iter.hadobles.size() > i; i++) {
            jComboBoxDob.addItem(Iter.hadobles.get(i).toString());
        }
        for (int i = 0; Iter.hamatri.size() > i; i++) {
            jComboBoxmat.addItem(Iter.hamatri.get(i).toString());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupHabit = new javax.swing.ButtonGroup();
        jComboBoxSim = new javax.swing.JComboBox<>();
        jComboBoxDob = new javax.swing.JComboBox<>();
        jComboBoxmat = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldDocR = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jRadioButtonSim = new javax.swing.JRadioButton();
        jRadioButtondolb = new javax.swing.JRadioButton();
        jRadioButtonmatr = new javax.swing.JRadioButton();
        jTextFieldFin = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldFsa = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel4.setText("Número de habitación");

        jLabel5.setText("Documento");

        jLabel6.setText("Nombres");

        jTextField2.setEditable(false);

        jButton1.setText("Reservar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jRadioButtonSim.setText("simple");

        jRadioButtondolb.setText("doble");

        jRadioButtonmatr.setText("matrimonial");

        jLabel1.setText("Fecha ingreso");

        jLabel2.setText("Fecha salida");

        jButton2.setText("Eliminar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel5)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(24, 24, 24)
                            .addComponent(jLabel6)))
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldDocR, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jButton2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1))
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButtonSim)
                            .addComponent(jComboBoxSim, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBoxDob, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jRadioButtondolb))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBoxmat, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jRadioButtonmatr)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextFieldFin, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldFsa, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonSim)
                    .addComponent(jRadioButtondolb)
                    .addComponent(jRadioButtonmatr))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxSim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxDob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxmat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextFieldDocR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldFsa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(31, 31, 31))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String NumH = "";
        String tipoper = "";
        String TipoHabita = "";
        if (jRadioButtonSim.isSelected()) {
            TipoHabita = "SIMPLE";
            NumH = jComboBoxSim.getSelectedItem().toString();
        }
        if (jRadioButtondolb.isSelected()) {
            TipoHabita = "DOBLE";
            NumH = jComboBoxDob.getSelectedItem().toString();
        }
        if (jRadioButtonmatr.isSelected()) {
            TipoHabita = "MATRIMONIAL";
            NumH = jComboBoxmat.getSelectedItem().toString();
        }
        String docr = jTextFieldDocR.getText();
        Iter.reservas.add("start");
        Iter.reservas.add(docr);
        Iter.reservas.add(NumH);
        Iter.reservas.add(jTextFieldFin.getText());
        Iter.reservas.add(jTextFieldFsa.getText());
        for (int i = 0; Iter.Personas.size() > i; i++) {
            if (Iter.Personas.get(i).toString().equals(docr)) {
                int r = i + 4;
                tipoper = Iter.Personas.get(r).toString();
                System.out.println("tipo de persona obtenida de la array personas " + tipoper);
            }
        }
        if (TipoHabita.equals("SIMPLE")) {
            if (tipoper.equals("esporadico")) {
                Iter.reservas.add(Iter.ValSimpespo);
            } else {
                Iter.reservas.add(Iter.ValSimphabi);
            }
        }
        if (TipoHabita.equals("DOBLE")) {
            if (tipoper.equals("esporadico")) {
                Iter.reservas.add(Iter.ValDobleespo);
            } else {
                Iter.reservas.add(Iter.ValDoblehabi);
            }
        }
        if (TipoHabita.equals("MATRIMONIAL")) {
            if (tipoper.equals("esporadico")) {
                Iter.reservas.add(Iter.ValMatriespo);
            } else {
                Iter.reservas.add(Iter.ValMatrihabi);
            }
        }
        System.out.println("datos dentro de la array reservas " + Iter.reservas);

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String DocDelete = jTextFieldDocR.getText();
        for (int i = 0; Iter.reservas.size() > i; i++) {
            if (Iter.reservas.get(i).toString().equals(DocDelete)) {
                System.out.println("dentro de if borrar reservas");
                for (int j = i; i == j; j++) {
                    int p = j - 1;
                    Iter.reservas.remove(p);
                    
                    Iter.reservas.remove(p);
                    
                    Iter.reservas.remove(p);
                    Iter.reservas.remove(p);
                    Iter.reservas.remove(p);
                    Iter.reservas.remove(p);
                    
                    //Iter.reservas.remove(p++);
  
                    //Iter.reservas.remove(p++);
                    //Iter.reservas.remove(p+1);
                }

            }
        }
        System.out.println("removido con exito");
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReseHabitaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReseHabitaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReseHabitaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReseHabitaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReseHabitaciones().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupHabit;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBoxDob;
    private javax.swing.JComboBox<String> jComboBoxSim;
    private javax.swing.JComboBox<String> jComboBoxmat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JRadioButton jRadioButtonSim;
    private javax.swing.JRadioButton jRadioButtondolb;
    private javax.swing.JRadioButton jRadioButtonmatr;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextFieldDocR;
    private javax.swing.JTextField jTextFieldFin;
    private javax.swing.JTextField jTextFieldFsa;
    // End of variables declaration//GEN-END:variables
}
